"""empty message

Revision ID: 55b0fff28a19
Revises: 5303a89af2cf
Create Date: 2015-11-18 09:10:40.585699

"""

# revision identifiers, used by Alembic.
revision = '55b0fff28a19'
down_revision = '5303a89af2cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workgroup_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workgroup_name')
    )
    op.add_column(u'users', sa.Column('workgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'workgroups', ['workgroup_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'workgroup_id')
    op.drop_table('workgroups')
    ### end Alembic commands ###
